### ISSUE TITLE
Pasar memoria word a Latex

### ISSUE THREAD

**Issue by iml1012** [luisfbarrero/GESPRO_GESTIONTAREAS#32]
Revisar imágenes.
Revisar bibliografía.
bibentry (http://gking.harvard.edu/files/bibentry2.pdf).
Documentación
 Resumen
 Introducción
 Objetivos del proyecto
 Conceptos teóricos
 Técnicas y herramientas
 Aspectos relevantes
 Trabajos relacionados
 Conclusiones y Líneas de trabajo futuras

**Comment by iml1012** [comment]
Expresión regular para corregir las referencias:

Buscar: (\{\[\})([\w:\\]+)(\{\]\}\\\_)
Reemplazar por: \\citep{\2}
Ej: {[}art:campbell2005{]}\_ -> \citep{art:campbell2005}

Expresión regular para corregir las imágenes:

Buscar: (\\includegraphics{..\/..\/img\/)(\w*)(.\w*\})
Reemplazar por: \\imagen{\2}{descripción...}
Ej: \includegraphics{../../img/s2.png} -> \imagen{s2}{descripción...}}

**Comment by luisfbarrero** [comment]
Verificada parte 1
